"""
Django settings for digitaltwin_backend project.

Generated by 'django-admin startproject' using Django 4.2.28.
"""

import os
from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-!bgapec)y&m_(fu82&*8mt#7k2^bh2w#)8lntj$_6j445*i@&m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders', # Add this
    'ninja_jwt',
    'ninja_extra',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digitaltwin_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

WSGI_APPLICATION = 'digitaltwin_backend.wsgi.application'

# ASGI Setup
ASGI_APPLICATION = 'digitaltwin_backend.asgi.application'

REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=0, cast=int)
REDIS_PASSWORD = config('REDIS_PASSWORD', default='')

REDIS_URL = f'redis://{":" if REDIS_PASSWORD else ""}{REDIS_PASSWORD if REDIS_PASSWORD else ""}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# Database
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.postgresql':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': config('DB_NAME', default='digitaltwin_dev'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL', default='sqlite:///db.sqlite3'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)

if config('SECURE_HSTS_SECONDS', default=''):
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=0, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = config('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False, cast=bool)
    SECURE_HSTS_PRELOAD = config('SECURE_HSTS_PRELOAD', default=False, cast=bool)

# Logging Configuration
LOG_LEVEL = config('LOG_LEVEL', default='INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=1025, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Celery Configuration
CELERY_BROKER_URL = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# MQTT Configuration
MQTT_BROKER_HOST = config('MQTT_BROKER_HOST', default='localhost')
MQTT_BROKER_PORT = config('MQTT_BROKER_PORT', default=1883, cast=int)
MQTT_USERNAME = config('MQTT_USERNAME', default='')
MQTT_PASSWORD = config('MQTT_PASSWORD', default='')
MQTT_CLIENT_ID = config('MQTT_CLIENT_ID', default='digitaltwin-backend-worker')
MQTT_KEEPALIVE = config('MQTT_KEEPALIVE', default=60, cast=int)
MQTT_CLEAN_SESSION = config('MQTT_CLEAN_SESSION', default=False, cast=bool)
MQTT_TRANSPORT = config('MQTT_TRANSPORT', default='tcp')

MQTT_TELEMETRY_STATE_TOPIC = config('MQTT_TELEMETRY_STATE_TOPIC', default='plant/telemetry/state')
MQTT_TELEMETRY_HEALTH_TOPIC = config('MQTT_TELEMETRY_HEALTH_TOPIC', default='plant/telemetry/health')
MQTT_COMMAND_TOPIC = config('MQTT_COMMAND_TOPIC', default='plant/command/set_mode')

MQTT_TELEMETRY_QOS = config('MQTT_TELEMETRY_QOS', default=1, cast=int)
MQTT_COMMAND_QOS = config('MQTT_COMMAND_QOS', default=2, cast=int)

MQTT_COMMAND_POLL_INTERVAL_SECONDS = config('MQTT_COMMAND_POLL_INTERVAL_SECONDS', default=1.0, cast=float)
MQTT_COMMAND_BATCH_SIZE = config('MQTT_COMMAND_BATCH_SIZE', default=20, cast=int)
MQTT_PUBLISH_ACK_TIMEOUT_SECONDS = config('MQTT_PUBLISH_ACK_TIMEOUT_SECONDS', default=10.0, cast=float)

MQTT_TLS_ENABLED = config('MQTT_TLS_ENABLED', default=True, cast=bool)
MQTT_TLS_CA_CERT = config('MQTT_TLS_CA_CERT', default='')
MQTT_TLS_CERTFILE = config('MQTT_TLS_CERTFILE', default='')
MQTT_TLS_KEYFILE = config('MQTT_TLS_KEYFILE', default='')
MQTT_TLS_INSECURE = config('MQTT_TLS_INSECURE', default=False, cast=bool)
MQTT_TLS_VERSION = config('MQTT_TLS_VERSION', default='TLSv1_2')
# In settings.py
MQTT_CLEAN_SESSION = config('MQTT_CLEAN_SESSION', default=True, cast=bool)

MQTT_RECONNECT_DELAY_MIN_SECONDS = config('MQTT_RECONNECT_DELAY_MIN_SECONDS', default=1, cast=int)
MQTT_RECONNECT_DELAY_MAX_SECONDS = config('MQTT_RECONNECT_DELAY_MAX_SECONDS', default=60, cast=int)

# Application Settings
ENVIRONMENT = config('ENVIRONMENT', default='development')
API_TIMEOUT = config('API_TIMEOUT', default=30, cast=int)
MAX_WORKERS = config('MAX_WORKERS', default=4, cast=int)

CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='http://localhost:8080').split(',')
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:8080').split(',')
