# Generated by Django 4.2.17 on 2026-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SYSTEM_OFF', 'SYSTEM_OFF'), ('IDLE', 'IDLE'), ('FILLING', 'FILLING'), ('LOW_SUPPLY', 'LOW_SUPPLY'), ('LOCAL_AUTONOMOUS', 'LOCAL_AUTONOMOUS'), ('FAULT', 'FAULT'), ('MANUAL_OVERRIDE', 'MANUAL_OVERRIDE')], max_length=32)),
                ('tank1_level', models.FloatField()),
                ('tank2_level', models.FloatField()),
                ('source_level', models.FloatField()),
                ('low_source_flag', models.BooleanField(default=False)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('cloud_connection_status', models.CharField(choices=[('CONNECTED', 'CONNECTED'), ('LOST', 'LOST')], max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
