# Generated by Django 4.2.28 on 2026-04-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('REQUEST_MODE_CHANGE', 'REQUEST_MODE_CHANGE'), ('REQUEST_SUPPLY_TO_TANK', 'REQUEST_SUPPLY_TO_TANK'), ('REQUEST_STOP', 'REQUEST_STOP'), ('SYSTEM_SHUTDOWN', 'SYSTEM_SHUTDOWN'), ('MODIFY_CONSTANTS', 'MODIFY_CONSTANTS')], max_length=64)),
                ('payload', models.JSONField()),
                ('issued_by', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=16)),
                ('reason', models.TextField(null=True)),
                ('mqtt_published', models.BooleanField(default=False)),
                ('mqtt_last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(max_length=64)),
                ('detected_by', models.CharField(default='EDGE', max_length=16)),
                ('snapshot', models.JSONField()),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, 'IDLE'), (1, 'HYDRAULIC_TRANSITION'), (2, 'FILLING'), (3, 'LOW_SUPPLY'), (4, 'FAULT')], default=0)),
                ('source_level_percent', models.FloatField(default=0.0)),
                ('source_fault', models.BooleanField(default=False)),
                ('pump_actual', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, 'IDLE'), (1, 'HYDRAULIC_TRANSITION'), (2, 'FILLING'), (3, 'LOW_SUPPLY'), (4, 'FAULT')])),
                ('source_level_percent', models.FloatField()),
                ('pump_actual', models.BooleanField()),
                ('tanks_snapshot', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TankState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.PositiveSmallIntegerField()),
                ('level_percent', models.FloatField(default=0.0)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'OK'), (1, 'SENSOR_FAULT'), (2, 'VALVE_FAULT'), (3, 'COMM_LOST')], default=0)),
                ('valve_actual', models.BooleanField(default=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='core.systemstate')),
            ],
        ),
    ]
