# Generated by Django 4.2.17 on 2026-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('REQUEST_MODE_CHANGE', 'REQUEST_MODE_CHANGE'), ('REQUEST_SUPPLY', 'REQUEST_SUPPLY'), ('REQUEST_STOP', 'REQUEST_STOP'), ('ENABLE_MANUAL_OVERRIDE', 'ENABLE_MANUAL_OVERRIDE'), ('DISABLE_MANUAL_OVERRIDE', 'DISABLE_MANUAL_OVERRIDE'), ('SYSTEM_SHUTDOWN', 'SYSTEM_SHUTDOWN')], max_length=64)),
                ('payload', models.JSONField()),
                ('issued_by', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], max_length=16)),
                ('reason', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaultLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(max_length=64)),
                ('detected_by', models.CharField(max_length=16)),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
