# Generated by Django 4.2.28 on 2026-04-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemstate',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'IDLE'), (1, 'HYDRAULIC_TRANSITION'), (2, 'FILLING'), (3, 'LOW_SUPPLY'), (4, 'FAULT'), (5, 'Pump Spin Down')], default=0),
        ),
        migrations.AlterField(
            model_name='telemetrylog',
            name='mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'IDLE'), (1, 'HYDRAULIC_TRANSITION'), (2, 'FILLING'), (3, 'LOW_SUPPLY'), (4, 'FAULT'), (5, 'Pump Spin Down')]),
        ),
    ]
