# Generated by Django 4.2.17 on 2026-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_command_faultlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstate',
            name='low_source_flag',
        ),
        migrations.AddField(
            model_name='systemstate',
            name='pump_actual',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FAULT', 'FAULT')], default='OFF', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='pump_command',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FAULT', 'FAULT')], default='OFF', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='source_sensor_status',
            field=models.CharField(choices=[('OK', 'OK'), ('FAULT', 'FAULT')], default='OK', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='tank1_sensor_status',
            field=models.CharField(choices=[('OK', 'OK'), ('FAULT', 'FAULT')], default='OK', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='tank2_sensor_status',
            field=models.CharField(choices=[('OK', 'OK'), ('FAULT', 'FAULT')], default='OK', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='valve1_actual',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FAULT', 'FAULT')], default='CLOSED', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='valve1_command',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FAULT', 'FAULT')], default='CLOSED', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='valve2_actual',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FAULT', 'FAULT')], default='CLOSED', max_length=8),
        ),
        migrations.AddField(
            model_name='systemstate',
            name='valve2_command',
            field=models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('FAULT', 'FAULT')], default='CLOSED', max_length=8),
        ),
        migrations.AlterField(
            model_name='systemstate',
            name='cloud_connection_status',
            field=models.CharField(choices=[('CONNECTED', 'CONNECTED'), ('LOST', 'LOST')], default='CONNECTED', max_length=16),
        ),
    ]
