# Generated by Django 4.2.28 on 2026-04-08 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_command_mqtt_publish_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='command',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PUBLISHED', 'Published to MQTT'), ('ACKNOWLEDGED', 'Acknowledged by Edge'), ('EXECUTING', 'Executing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=16),
        ),
    ]
