# Generated by Django 4.2.28 on 2026-02-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_systemstate_low_source_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('value', models.FloatField()),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('tank1_level', models.FloatField()),
                ('tank2_level', models.FloatField()),
                ('source_level', models.FloatField()),
                ('pump_actual', models.CharField(max_length=8)),
                ('valve1_actual', models.CharField(max_length=8)),
                ('valve2_actual', models.CharField(max_length=8)),
                ('mode', models.CharField(max_length=32)),
                ('cloud_connection_status', models.CharField(default='CONNECTED', max_length=16)),
                ('emergency_stop', models.BooleanField(default=False)),
                ('low_src_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='faultlog',
            old_name='created_at',
            new_name='ts',
        ),
    ]
