# Generated by Django 4.2.28 on 2026-02-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_systemconfig_telemetrylog_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="command",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("REQUEST_MODE_CHANGE", "REQUEST_MODE_CHANGE"),
                    ("REQUEST_SUPPLY_TO_TANK", "REQUEST_SUPPLY_TO_TANK"),
                    ("REQUEST_SUPPLY", "REQUEST_SUPPLY"),
                    ("REQUEST_STOP", "REQUEST_STOP"),
                    ("ENABLE_MANUAL_OVERRIDE", "ENABLE_MANUAL_OVERRIDE"),
                    ("DISABLE_MANUAL_OVERRIDE", "DISABLE_MANUAL_OVERRIDE"),
                    ("SYSTEM_SHUTDOWN", "SYSTEM_SHUTDOWN"),
                    ("SET_PRIORITY", "SET_PRIORITY"),
                    ("MODIFY_CONSTANTS", "MODIFY_CONSTANTS"),
                ],
                max_length=64,
            ),
        ),
    ]
