# Generated by Django 4.2.28 on 2026-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_command_command_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="command",
            name="mqtt_last_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="command",
            name="mqtt_publish_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="command",
            name="mqtt_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="command",
            name="mqtt_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="command",
            name="mqtt_qos",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="command",
            name="mqtt_topic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

